name: generate-snake

on:
  schedule:
    - cron: "0 0 * * 1"   # 每周一次
  workflow_dispatch:

permissions:
  contents: write         # 允许提交代码

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: zxidd24
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update snake" || echo "no changes"
          git pull --rebase
          git push
